# Generated by Django 5.1.1 on 2024-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True, unique=True
            ),
        ),
    ]
