# Generated by Django 5.1.1 on 2024-10-07 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("post_type_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("image", "image"),
                            ("video", "video"),
                            ("carousel", "carousel"),
                            ("reels", "reels"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post_caption",
                    models.TextField(blank=True, max_length=1600, null=True),
                ),
                ("is_comment_allowed", models.BooleanField(default=True)),
                ("is_post_share_as_msg_allowed", models.BooleanField(default=True)),
                ("is_liked_allowed", models.BooleanField(default=True)),
                ("is_saved_allowed", models.BooleanField(default=True)),
                (
                    "is_post_share_on_other_platform_allowed",
                    models.BooleanField(default=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_posted_by_model_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_app.posttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
