# Generated by Django 5.1.1 on 2024-10-08 06:58

import django.db.models.deletion
import utils.utility_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostFiles",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("post_file_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "media_url",
                    models.FileField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        upload_to=utils.utility_functions.path_and_rename,
                    ),
                ),
                ("media_type", models.CharField(max_length=30)),
                ("media_thumbnail_url", models.URLField(max_length=500, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_files_post_model_manager",
                        to="post_app.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
